name: Build and Test

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.13

      - name: Install
        run: yarn bootstrap:ci

      - name: Lint
        run: yarn lint

      - name: Build Packages
        run: yarn build

      - name: Build Storybook
        run: yarn storybook:build

      - name: Start Storybook
        run: ls -la out/docs && yarn storybook:serve

      - name: Unit Tests
        run: yarn test

      - name: Functional Tests
        run: yarn test:functional

      - name: Terminate Storybook
        run: yarn storybook:terminate
